### ISSUE TITLE
TypeError: add_import() takes from 2 to 3 positional arguments but 5 were given

### ISSUE THREAD

**Issue by JPFrancoia** [laffra/auger#20]
I'm trying to run Auger on my code. I did exactly like in the README, but auger crashes on:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/run/media/djipey/50651dc3-df15-45e7-8e96-a50f832d261d/test/__main__.py", line 51, in <module>
    main()
  File "/run/media/djipey/50651dc3-df15-45e7-8e96-a50f832d261d/test/.venv/lib/python3.7/site-packages/auger/__init__.py", line 64, in __exit__
    sys.settrace(None)
  File "/run/media/djipey/50651dc3-df15-45e7-8e96-a50f832d261d/test/.venv/lib/python3.7/site-packages/auger/generator/default.py", line 34, in dump
    self.add_import(*(line.replace('from ', '').replace('import ','').split(' ')))
TypeError: add_import() takes from 2 to 3 positional arguments but 5 were given
```
Is it a known issue?

**Comment by NextDesign1** [comment]
Do you have a test case that I can take a look at?

**Comment by JPFrancoia** [comment]
I do. Please keep in mind that it was originally confidential code and that I made it dumb and anonymous, but the issue is reproduced here:

This is `test.py`:
```python
from upper import UpperObject

def main():

    to_up = "hello world"

    up = UpperObject()
    upped = up.parse(to_up)


if __name__ == "__main__":
    import auger

    print("coucou")

    with auger.magic([UpperObject], verbose=True):
        main()
```

And this is `upper.py`:

```python
from typing import List, Dict


class UpperObject:

    def __init__(self) -> None:
        pass

    def parse(self, to_up: str) -> str:

        upped = to_up.upper()

        return upped
```

I can already tell you that line 1 in `upper.py` causes the issue. Auger doesn't like multiple imports on a single line. Separating them on several lines works.

**Comment by NextDesign1** [comment]
Thanks for that JP. I have just opened a pull request to fix this issue. Please note however that auger is acting a bit strange with Python 3 at the moment. Please see issue #22.

**Comment by NextDesign1** [comment]
Closing as #21 has been merged.
