### ISSUE TITLE
wrapper_descriptor object has no attribute '__code__'

### ISSUE THREAD

**Issue by diyseguy** [laffra/auger#4]
Gosh I want this to work... what am I missing?

C:\cygwin64\home\julie\python\auger\venv\Scripts\python.exe C:/cygwin64/home/julie/python/auger/sample/calc_test_gen.py
Traceback (most recent call last):
  File "C:/cygwin64/home/julie/python/auger/sample/calc_test_gen.py", line 13, in <module>
    main();
  File "C:\cygwin64\home\julie\python\auger\auger\__init__.py", line 42, in __exit__
    sys.settrace(None)
  File "C:\cygwin64\home\julie\python\auger\auger\generator\default.py", line 21, in dump
    self.dump_tests(filename, functions)
  File "C:\cygwin64\home\julie\python\auger\auger\generator\default.py", line 144, in dump_tests
    instances = self.collect_instances(functions)
  File "C:\cygwin64\home\julie\python\auger\auger\generator\default.py", line 45, in collect_instances
    if init.__code__ == code:
AttributeError: 'wrapper_descriptor' object has no attribute '__code__'

Process finished with exit code 1

**Comment by darkvertex** [comment]
I'm getting this same error also, on both Windows and Linux.

**Comment by NextDesign1** [comment]
I'm also running into this with pretty much all code other than the provided examples. As a work-around, you can try jumping back to commit dadbbc4, before collect_instances was updated to reference __code__.

**Comment by laffra** [comment]
Let me replicate the issue and take a look.

**Comment by laffra** [comment]
I have not been able to replicate this error, but I pushed a change to head in [c3978a1](https://github.com/laffra/auger/commit/c3978a145a950e33ab7f534131addd3abc106e35) that should avoid this case. So, please try again....

**Comment by darkvertex** [comment]
Spoke too soon. Indeed I don't error like before, but the test code produced is a bit broken.

Gonna share here so you can investigate. I tried auger with a semi-complicated small Python class I have that fetches me my bus schedule from the Montreal bus website. Maybe it's not the best thing since it's not deterministic but the API I'm querying should always try to report some buses, and it should exhibit the problem.

Anyway, here goes a few files... (Requires [requests](https://pypi.org/project/requests/) and [humanize](https://pypi.org/project/humanize/) on Python 2.7 to run.)

First my one file module `stmbus.py`:
```python
import json
from datetime import datetime, timedelta

try:
    import humanize
except ImportError:
    humanize = None

import click
import requests


class STMBus(object):

    def __init__(self, line, stop, direction, maxResults=5):
        self.busLine = line
        self.busStop = stop
        self.direction = direction.lower()
        self._today = datetime.today().strftime(r'%Y%m%d')
        self._maxResults = maxResults
        self._userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36'
        self._apiURLTemplate = 'https://api.stm.info/pub/i3/v1c/api/en/lines/{line}/stops/{stop}/arrivals?d={today}&t=0000&direction={direction}&wheelchair=0&limit={limit}'
        self._refererURLTemplate = 'http://beta.stm.info/en/info/networks/bus/shuttle/line-{line}-{direction}/{stop}'
        self._rawData = {}

    @property
    def api_url(self):
        return self._apiURLTemplate.format(
            line=self.busLine, stop=self.busStop, direction=self.direction[0].upper(), today=self._today, limit=self._maxResults)

    @property
    def referer_url(self):
        return self._refererURLTemplate.format(line=self.busLine, direction=self.direction, stop=self.busStop)

    @property
    def request_headers(self):
        return {'Origin': 'http://beta.stm.info', 'User-Agent': self._userAgent, 'Referer': self.referer_url}

    def getAPIResponse(self, asJSON=False):
        page = requests.get(self.api_url, headers=self.request_headers)
        text = page.content
        if asJSON:
            return json.loads(text)
        return text

    def getJSON(self, force=False):
        if not self._rawData or force:
            self._rawData = self.getAPIResponse(asJSON=True)
        return self._rawData

    @property
    def prettyJSON(self):
        return json.dumps(self.getJSON(), indent=4)

    @property
    def schedule(self):
        return self.getJSON()['result']

    @property
    def nextBusInRealtime(self):
        for entry in self.schedule:
            if entry['is_real']:
                return int(entry['time'].strip('<'))

    @staticmethod
    def futureHourMinToDatetime(hour, minute):
        now = datetime.now()
        then = datetime.now().replace(hour=hour, minute=minute)
        if then < now:
            then += timedelta(days=1)
        return then

    def printSchedule(self):
        print 'Next {line} bus going {direction} at stop {stop}:\n'.format(
            line=self.busLine, direction=self.direction, stop=self.busStop)

        for entry in self.schedule:
            text = ''
            if entry['is_real']:
                if entry['is_congestion']:
                    text += 'Realtime:  {0}h{1}m'.format(
                        entry['time'][:2], entry['time'][2:])
                else:
                    text += 'Realtime:  {0}m'.format(entry['time'])
            else:
                text += 'Scheduled: {0}h{1}m'.format(entry['time'][:2], entry['time'][2:])
                if humanize:
                    hour = int(entry['time'][:2])
                    minute = int(entry['time'][2:])
                    then = self.futureHourMinToDatetime(hour, minute)
                    text += ' ({0})'.format(humanize.naturaltime(then))

            if entry['is_cancelled']:
                text += ' but is CANCELLED! :('

            if entry['is_real'] and entry['is_congestion']:
                text += ' (but there is congestion!)'

            if entry['is_at_stop']:
                text += ' and IT IS AT THE STOP! (GO GO GO!!)'

            if text:
                print text

        print '\nSource:', self.referer_url
```
(Nothing terribly complex, just querying a web API for some JSON and printing it.)

And here is `stmbus_auger_test.py`, with:
```python
import auger
import stmbus

def main():
    bus = stmbus.STMBus(715, 52975, 'east', maxResults=4)
    bus.printSchedule()

if __name__ == '__main__':
    with auger.magic([stmbus]):
        main()
```

---

This produced me a `test_stmbus.py` file which is *almost* good:

```python
import click
import datetime
import humanize.time
import json
from mock import patch
import requests
import requests.api
import requests.models
import stmbus
from stmbus import STMBus
import unittest


class StmbusTest(unittest.TestCase):
    def test_api_url(self):
        self.assertEquals(
            stmbus.api_url(self=<stmbus.STMBus object at 0x3420890>),
            'https://api.stm.info/pub/i3/v1c/api/en/lines/715/stops/52975/arrivals?d=20181017&t=0000&direction=E&wheelchair=0&limit=4'
        )


    def test_futureHourMinToDatetime(self):
        self.assertEquals(
            STMBus.futureHourMinToDatetime(minute=15,hour=15),
            datetime.datetime(2018, 10, 17, 15, 15, 23, 85224)
        )


    @patch.object(json, 'loads')
    @patch.object(requests.models, 'content')
    @patch.object(requests.api, 'get')
    def test_getAPIResponse(self, mock_get, mock_content, mock_loads):
        mock_get.return_value = <Response [200]>
        mock_content.return_value = '{"result":[{"time":"1444","is_real":false,"is_planified":true,"is_congestion":false,"is_at_stop":false,"is_cancelled":false,"is_ramp_cancelled":false,"is_last":false,"trip_id":"189093739","note":[]},{"time":"1515","is_real":false,"is_planified":true,"is_congestion":false,"is_at_stop":false,"is_cancelled":false,"is_ramp_cancelled":false,"is_last":false,"trip_id":"189093708","note":[]},{"time":"1545","is_real":false,"is_planified":true,"is_congestion":false,"is_at_stop":false,"is_cancelled":false,"is_ramp_cancelled":false,"is_last":false,"trip_id":"189093741","note":[]},{"time":"1615","is_real":false,"is_planified":true,"is_congestion":false,"is_at_stop":false,"is_cancelled":false,"is_ramp_cancelled":false,"is_last":false,"trip_id":"189093710","note":[]}],"global_is_congestion":false,"type":"Arrivals","status":{"level":"OK"},"messages":{"line":[{"text":"We are currently experiencing technical difficulties affecting real-time bus schedules and bus position info in real time. We are working to resolve this situation.","priority":"20","level":"StopRoute","logic_number":"2","start_date":"20181017"},{"text":"Because of roadwork, some bus stops have been relocated: 60713 (Centre infotouriste de Montr\xc3\xa9al (Metcalfe/Dorchest). In effect from 26 May 2018 at 23 h 49 for an indefinite period","priority":"10","level":"OTRM","logic_number":"4339258","start_date":"20180526"},{"text":"Because of roadwork, some bus stops have been relocated: 52619 (Peel / Saint-Antoine). In effect from 27 April 2018 at 14 h 13 for an indefinite period","priority":"10","level":"OTRM","logic_number":"4337282","start_date":"20180427"},{"text":"Because of roadwork, some bus stops have been relocated: 52992 (Wellington / des Soeurs-Grises). In effect from 13 September 2017 at 14 h 20 for an indefinite period","priority":"10","level":"OTRM","logic_number":"4320334","start_date":"20170913"}]},"stopName":"Wellington / Queen","line":{"public_identifier":"715","description":"Vieux-Montr\xc3\xa9al / Vieux-Port","direction_name":"East","category":"dedicated","main_category":"dedicated"}}'
        mock_loads.return_value = {u'status': {u'level': u'OK'}, u'stopName': u'Wellington / Queen', u'global_is_congestion': False, u'messages': {u'line': [{u'priority': u'20', u'text': u'We are currently experiencing technical difficulties affecting real-time bus schedules and bus position info in real time. We are working to resolve this situation.', u'logic_number': u'2', u'start_date': u'20181017', u'level': u'StopRoute'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 60713 (Centre infotouriste de Montr\xe9al (Metcalfe/Dorchest). In effect from 26 May 2018 at 23 h 49 for an indefinite period', u'logic_number': u'4339258', u'start_date': u'20180526', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52619 (Peel / Saint-Antoine). In effect from 27 April 2018 at 14 h 13 for an indefinite period', u'logic_number': u'4337282', u'start_date': u'20180427', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52992 (Wellington / des Soeurs-Grises). In effect from 13 September 2017 at 14 h 20 for an indefinite period', u'logic_number': u'4320334', u'start_date': u'20170913', u'level': u'OTRM'}]}, u'result': [{u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1444', u'is_real': False, u'is_planified': True, u'trip_id': u'189093739'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1515', u'is_real': False, u'is_planified': True, u'trip_id': u'189093708'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1545', u'is_real': False, u'is_planified': True, u'trip_id': u'189093741'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1615', u'is_real': False, u'is_planified': True, u'trip_id': u'189093710'}], u'line': {u'category': u'dedicated', u'public_identifier': u'715', u'main_category': u'dedicated', u'description': u'Vieux-Montr\xe9al / Vieux-Port', u'direction_name': u'East'}, u'type': u'Arrivals'}
        stmbus_instance = STMBus(715, 52975, 'east', 4)
        self.assertEquals(
            stmbus_instance.getAPIResponse(asJSON=True),
            {u'status': {u'level': u'OK'}, u'stopName': u'Wellington / Queen', u'global_is_congestion': False, u'messages': {u'line': [{u'priority': u'20', u'text': u'We are currently experiencing technical difficulties affecting real-time bus schedules and bus position info in real time. We are working to resolve this situation.', u'logic_number': u'2', u'start_date': u'20181017', u'level': u'StopRoute'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 60713 (Centre infotouriste de Montr\xe9al (Metcalfe/Dorchest). In effect from 26 May 2018 at 23 h 49 for an indefinite period', u'logic_number': u'4339258', u'start_date': u'20180526', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52619 (Peel / Saint-Antoine). In effect from 27 April 2018 at 14 h 13 for an indefinite period', u'logic_number': u'4337282', u'start_date': u'20180427', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52992 (Wellington / des Soeurs-Grises). In effect from 13 September 2017 at 14 h 20 for an indefinite period', u'logic_number': u'4320334', u'start_date': u'20170913', u'level': u'OTRM'}]}, u'result': [{u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1444', u'is_real': False, u'is_planified': True, u'trip_id': u'189093739'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1515', u'is_real': False, u'is_planified': True, u'trip_id': u'189093708'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1545', u'is_real': False, u'is_planified': True, u'trip_id': u'189093741'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1615', u'is_real': False, u'is_planified': True, u'trip_id': u'189093710'}], u'line': {u'category': u'dedicated', u'public_identifier': u'715', u'main_category': u'dedicated', u'description': u'Vieux-Montr\xe9al / Vieux-Port', u'direction_name': u'East'}, u'type': u'Arrivals'}
        )


    def test_getJSON(self):
        stmbus_instance = STMBus(715, 52975, 'east', 4)
        self.assertEquals(
            stmbus_instance.getJSON(force=False),
            {u'status': {u'level': u'OK'}, u'stopName': u'Wellington / Queen', u'global_is_congestion': False, u'messages': {u'line': [{u'priority': u'20', u'text': u'We are currently experiencing technical difficulties affecting real-time bus schedules and bus position info in real time. We are working to resolve this situation.', u'logic_number': u'2', u'start_date': u'20181017', u'level': u'StopRoute'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 60713 (Centre infotouriste de Montr\xe9al (Metcalfe/Dorchest). In effect from 26 May 2018 at 23 h 49 for an indefinite period', u'logic_number': u'4339258', u'start_date': u'20180526', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52619 (Peel / Saint-Antoine). In effect from 27 April 2018 at 14 h 13 for an indefinite period', u'logic_number': u'4337282', u'start_date': u'20180427', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52992 (Wellington / des Soeurs-Grises). In effect from 13 September 2017 at 14 h 20 for an indefinite period', u'logic_number': u'4320334', u'start_date': u'20170913', u'level': u'OTRM'}]}, u'result': [{u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1444', u'is_real': False, u'is_planified': True, u'trip_id': u'189093739'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1515', u'is_real': False, u'is_planified': True, u'trip_id': u'189093708'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1545', u'is_real': False, u'is_planified': True, u'trip_id': u'189093741'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1615', u'is_real': False, u'is_planified': True, u'trip_id': u'189093710'}], u'line': {u'category': u'dedicated', u'public_identifier': u'715', u'main_category': u'dedicated', u'description': u'Vieux-Montr\xe9al / Vieux-Port', u'direction_name': u'East'}, u'type': u'Arrivals'}
        )


        stmbus_instance = STMBus(715, 52975, 'east', 4)
        self.assertEquals(
            stmbus_instance.getJSON(force=False),
            {u'status': {u'level': u'OK'}, u'stopName': u'Wellington / Queen', u'global_is_congestion': False, u'messages': {u'line': [{u'priority': u'20', u'text': u'We are currently experiencing technical difficulties affecting real-time bus schedules and bus position info in real time. We are working to resolve this situation.', u'logic_number': u'2', u'start_date': u'20181017', u'level': u'StopRoute'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 60713 (Centre infotouriste de Montr\xe9al (Metcalfe/Dorchest). In effect from 26 May 2018 at 23 h 49 for an indefinite period', u'logic_number': u'4339258', u'start_date': u'20180526', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52619 (Peel / Saint-Antoine). In effect from 27 April 2018 at 14 h 13 for an indefinite period', u'logic_number': u'4337282', u'start_date': u'20180427', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52992 (Wellington / des Soeurs-Grises). In effect from 13 September 2017 at 14 h 20 for an indefinite period', u'logic_number': u'4320334', u'start_date': u'20170913', u'level': u'OTRM'}]}, u'result': [{u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1444', u'is_real': False, u'is_planified': True, u'trip_id': u'189093739'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1515', u'is_real': False, u'is_planified': True, u'trip_id': u'189093708'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1545', u'is_real': False, u'is_planified': True, u'trip_id': u'189093741'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1615', u'is_real': False, u'is_planified': True, u'trip_id': u'189093710'}], u'line': {u'category': u'dedicated', u'public_identifier': u'715', u'main_category': u'dedicated', u'description': u'Vieux-Montr\xe9al / Vieux-Port', u'direction_name': u'East'}, u'type': u'Arrivals'}
        )


    def test_nextBusInRealtime(self):
        self.assertEquals(
            stmbus.nextBusInRealtime(self=<stmbus.STMBus object at 0x3420890>),
            None
        )


    @patch.object(humanize.time, 'naturaltime')
    def test_printSchedule(self, mock_naturaltime):
        mock_naturaltime.return_value = '26 minutes from now'
        stmbus_instance = STMBus(715, 52975, 'east', 4)
        self.assertEquals(
            stmbus_instance.printSchedule(),
            None
        )


    def test_referer_url(self):
        self.assertEquals(
            stmbus.referer_url(self=<stmbus.STMBus object at 0x3420890>),
            'http://beta.stm.info/en/info/networks/bus/shuttle/line-715-east/52975'
        )


        self.assertEquals(
            stmbus.referer_url(self=<stmbus.STMBus object at 0x3420890>),
            'http://beta.stm.info/en/info/networks/bus/shuttle/line-715-east/52975'
        )


    def test_request_headers(self):
        self.assertEquals(
            stmbus.request_headers(self=<stmbus.STMBus object at 0x3420890>),
            {'Origin': 'http://beta.stm.info', 'Referer': 'http://beta.stm.info/en/info/networks/bus/shuttle/line-715-east/52975', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36'}
        )


    def test_schedule(self):
        self.assertEquals(
            stmbus.schedule(self=<stmbus.STMBus object at 0x3420890>),
            [{u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1444', u'is_real': False, u'is_planified': True, u'trip_id': u'189093739'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1515', u'is_real': False, u'is_planified': True, u'trip_id': u'189093708'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1545', u'is_real': False, u'is_planified': True, u'trip_id': u'189093741'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1615', u'is_real': False, u'is_planified': True, u'trip_id': u'189093710'}]
        )


        self.assertEquals(
            stmbus.schedule(self=<stmbus.STMBus object at 0x3420890>),
            [{u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1444', u'is_real': False, u'is_planified': True, u'trip_id': u'189093739'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1515', u'is_real': False, u'is_planified': True, u'trip_id': u'189093708'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1545', u'is_real': False, u'is_planified': True, u'trip_id': u'189093741'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1615', u'is_real': False, u'is_planified': True, u'trip_id': u'189093710'}]
        )


if __name__ == "__main__":
    unittest.main()
```

If you look closer you'll see lots of broken Python syntax with stuff like:
```
stmbus.api_url(self=<stmbus.STMBus object at 0x3420890>),
```
or
```
        mock_get.return_value = <Response [200]>
```


Perhaps it's a tad too complex for `auger` to handle, but it's a shame as it's _so_ close to being legit valid Python test code.

**Comment by laffra** [comment]
You uncovered new issues, such us support for 

- complex object types in mock return values, and
- @property methods

I pushed fixes for those and published oon PyPi, under version 0.1.29. 

Please try again...

**Comment by NextDesign1** [comment]
Thanks for looking into this @laffra.

I'm not seeing the additions you mentioned above here on Github. Did you push directly to PyPi?

**Comment by laffra** [comment]
Oops, forgot. Did the git push now as well.

**Comment by darkvertex** [comment]
Tried again and it's definitely less broken.

It produced me:
```python
class StmbusTest(unittest.TestCase):
    @patch.object(json, 'loads')
    @patch.object(PreparedRequest, 'content')
    @patch.object(requests.api, 'get')
    def test_getAPIResponse(self, mock_get, mock_content, mock_loads):
        mock_get.return_value = Response()
        mock_content.return_value = '{"result":[{"time":"6","is_real":true,"is_planified":false,"is_congestion":false,"is_at_stop":false,"is_cancelled":false,"is_ramp_cancelled":false,"is_last":false,"trip_id":"189093696","note":[]},{"time":"38","is_real":true,"is_planified":false,"is_congestion":false,"is_at_stop":false,"is_cancelled":false,"is_ramp_cancelled":false,"is_last":false,"trip_id":"189093729","note":[]},{"time":"1014","is_real":false,"is_planified":true,"is_congestion":false,"is_at_stop":false,"is_cancelled":false,"is_ramp_cancelled":false,"is_last":false,"trip_id":"189093698","note":[]},{"time":"1044","is_real":false,"is_planified":true,"is_congestion":false,"is_at_stop":false,"is_cancelled":false,"is_ramp_cancelled":false,"is_last":false,"trip_id":"189093731","note":[]}],"global_is_congestion":false,"type":"Arrivals","status":{"level":"OK"},"messages":{"line":[{"text":"Because of roadwork, some bus stops have been relocated: 60713 (Centre infotouriste de Montr\xc3\xa9al (Metcalfe/Dorchest). In effect from 26 May 2018 at 23 h 49 for an indefinite period","priority":"10","level":"OTRM","logic_number":"4339258","start_date":"20180526"},{"text":"Because of roadwork, some bus stops have been relocated: 52619 (Peel / Saint-Antoine). In effect from 27 April 2018 at 14 h 13 for an indefinite period","priority":"10","level":"OTRM","logic_number":"4337282","start_date":"20180427"},{"text":"Because of roadwork, some bus stops have been relocated: 52992 (Wellington / des Soeurs-Grises). In effect from 13 September 2017 at 14 h 20 for an indefinite period","priority":"10","level":"OTRM","logic_number":"4320334","start_date":"20170913"}]},"stopName":"Wellington / Queen","line":{"public_identifier":"715","description":"Vieux-Montr\xc3\xa9al / Vieux-Port","direction_name":"East","category":"dedicated","main_category":"dedicated"}}'
        mock_loads.return_value = {u'status': {u'level': u'OK'}, u'stopName': u'Wellington / Queen', u'global_is_congestion': False, u'messages': {u'line': [{u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 60713 (Centre infotouriste de Montr\xe9al (Metcalfe/Dorchest). In effect from 26 May 2018 at 23 h 49 for an indefinite period', u'logic_number': u'4339258', u'start_date': u'20180526', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52619 (Peel / Saint-Antoine). In effect from 27 April 2018 at 14 h 13 for an indefinite period', u'logic_number': u'4337282', u'start_date': u'20180427', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52992 (Wellington / des Soeurs-Grises). In effect from 13 September 2017 at 14 h 20 for an indefinite period', u'logic_number': u'4320334', u'start_date': u'20170913', u'level': u'OTRM'}]}, u'result': [{u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'6', u'is_real': True, u'is_planified': False, u'trip_id': u'189093696'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'38', u'is_real': True, u'is_planified': False, u'trip_id': u'189093729'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1014', u'is_real': False, u'is_planified': True, u'trip_id': u'189093698'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1044', u'is_real': False, u'is_planified': True, u'trip_id': u'189093731'}], u'line': {u'category': u'dedicated', u'public_identifier': u'715', u'main_category': u'dedicated', u'description': u'Vieux-Montr\xe9al / Vieux-Port', u'direction_name': u'East'}, u'type': u'Arrivals'}
        stmbus_instance = STMBus(715, 52975, 'east', 4)
        self.assertEquals(
            stmbus_instance.getAPIResponse(asJSON=True),
            {u'status': {u'level': u'OK'}, u'stopName': u'Wellington / Queen', u'global_is_congestion': False, u'messages': {u'line': [{u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 60713 (Centre infotouriste de Montr\xe9al (Metcalfe/Dorchest). In effect from 26 May 2018 at 23 h 49 for an indefinite period', u'logic_number': u'4339258', u'start_date': u'20180526', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52619 (Peel / Saint-Antoine). In effect from 27 April 2018 at 14 h 13 for an indefinite period', u'logic_number': u'4337282', u'start_date': u'20180427', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52992 (Wellington / des Soeurs-Grises). In effect from 13 September 2017 at 14 h 20 for an indefinite period', u'logic_number': u'4320334', u'start_date': u'20170913', u'level': u'OTRM'}]}, u'result': [{u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'6', u'is_real': True, u'is_planified': False, u'trip_id': u'189093696'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'38', u'is_real': True, u'is_planified': False, u'trip_id': u'189093729'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1014', u'is_real': False, u'is_planified': True, u'trip_id': u'189093698'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1044', u'is_real': False, u'is_planified': True, u'trip_id': u'189093731'}], u'line': {u'category': u'dedicated', u'public_identifier': u'715', u'main_category': u'dedicated', u'description': u'Vieux-Montr\xe9al / Vieux-Port', u'direction_name': u'East'}, u'type': u'Arrivals'}
        )


    def test_getJSON(self):
        stmbus_instance = STMBus(715, 52975, 'east', 4)
        self.assertEquals(
            stmbus_instance.getJSON(force=False),
            {u'status': {u'level': u'OK'}, u'stopName': u'Wellington / Queen', u'global_is_congestion': False, u'messages': {u'line': [{u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 60713 (Centre infotouriste de Montr\xe9al (Metcalfe/Dorchest). In effect from 26 May 2018 at 23 h 49 for an indefinite period', u'logic_number': u'4339258', u'start_date': u'20180526', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52619 (Peel / Saint-Antoine). In effect from 27 April 2018 at 14 h 13 for an indefinite period', u'logic_number': u'4337282', u'start_date': u'20180427', u'level': u'OTRM'}, {u'priority': u'10', u'text': u'Because of roadwork, some bus stops have been relocated: 52992 (Wellington / des Soeurs-Grises). In effect from 13 September 2017 at 14 h 20 for an indefinite period', u'logic_number': u'4320334', u'start_date': u'20170913', u'level': u'OTRM'}]}, u'result': [{u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'6', u'is_real': True, u'is_planified': False, u'trip_id': u'189093696'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'38', u'is_real': True, u'is_planified': False, u'trip_id': u'189093729'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1014', u'is_real': False, u'is_planified': True, u'trip_id': u'189093698'}, {u'is_ramp_cancelled': False, u'is_at_stop': False, u'note': [], u'is_cancelled': False, u'is_congestion': False, u'is_last': False, u'time': u'1044', u'is_real': False, u'is_planified': True, u'trip_id': u'189093731'}], u'line': {u'category': u'dedicated', u'public_identifier': u'715', u'main_category': u'dedicated', u'description': u'Vieux-Montr\xe9al / Vieux-Port', u'direction_name': u'East'}, u'type': u'Arrivals'}
        )


    @patch.object(humanize.time, 'naturaltime')
    def test_printSchedule(self, mock_naturaltime):
        mock_naturaltime.return_value = 'an hour from now'
        stmbus_instance = STMBus(715, 52975, 'east', 4)
        self.assertEquals(
            stmbus_instance.printSchedule(),
            None
        )
```

Apart from my code being non-deterministic (ie producing different results, since it calls an online API), the only "broken code" part here is the undefined `Response()` bit, but with a tiny bit of manual love it's very close to usable test code. I guess it's something from `requests` that didn't translate quite right.

It also looks like it's now just straight up ignoring `@property` methods... Is that the expected behaviour at this time?

**Comment by NextDesign1** [comment]
Sorry to revive this, but I don't know how to mention @darkvertex otherwise. I just tried your code with the latest auger version (0.1.31) which includes pull request #9, where I extended support for @property methods.

Your code now generates:

```
class StmbusTest(unittest.TestCase):
    def test_api_url(self):
        ...

    def test_futureHourMinToDatetime(self):
        ...

    @patch.object(requests.api, 'get')
    @patch.object(PreparedRequest, 'content')
    @patch.object(json, 'loads')
    def test_getAPIResponse(self, mock_loads, mock_content, mock_get):
        ...

    def test_getJSON(self):
        ...

    @patch.object(humanize.time, 'naturaltime')
    def test_printSchedule(self, mock_naturaltime):
        ...

    def test_referer_url(self):
        ...

    def test_request_headers(self):
        ...

    def test_schedule(self):
        ...

if __name__ == "__main__":
    unittest.main()
```
